version: 2

models:
  - name: stg_customers
    description: Customers data cleaned and normalized
    config:
      contract:
        enforced: true

    columns:
      - name: customer_id
        data_type: varchar
        description: Unique customer identifier
        tests:
          - not_null
          - unique
      - name: first_name
        data_type: varchar
        description: First name
        tests:
          - not_null
      - name: last_name
        data_type: varchar
        description: Last name
        tests:
          - not_null
      - name: email
        data_type: varchar
        description: Email address
        meta:
          pii: true
        tests:
          - not_null
          - unique
      - name: signup_date
        data_type: date
        description: Signup date
      - name: row_num
        data_type: BIGINT


  - name: stg_orders
    description: Orders data cleaned and normalized    
    config:
      contract:
        enforced: true
    columns:
      - name: order_id
        data_type: varchar
        description: Unique order identifier
        tests:
          - not_null
          - unique
      - name: customer_id
        data_type: varchar
        description: Unique customer identifier
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('stg_customers')
                field: customer_id
      - name: order_date
        data_type: date
        description: Order date
        tests:
          - not_null
      - name: status
        data_type: varchar
        description: Order status
        tests:
          - not_null
          - accepted_values:
              values: ['completed', 'pending', 'cancelled', 'returned']
      - name: total_amount 
        data_type: numeric
        description: Order total amount
        tests:
          - not_null

  - name: stg_order_items
    description: Order items data cleaned and normalized
    config:
      contract:
        enforced: true
    columns:
      - name: order_item_id
        data_type: varchar
        description: Unique order item identifier
        tests:
          - not_null
          - unique
      - name: order_id
        data_type: varchar
        description: Unique order identifier
        tests:
          - not_null

      - name: product_id
        data_type: varchar
        description: Unique product identifier
        tests:
          - not_null

      - name: quantity
        data_type: INTEGER
        description: Quantity ordered
        tests:
          - not_null
      - name: unit_price
        data_type: DECIMAL
        description: Unit price
        tests:
          - not_null
      - name: line_total
        data_type: DECIMAL
        description: Line total
        tests:
          - not_null

  - name: stg_products
    description: Products data cleaned and normalized
    config:
      contract:
        enforced: true
    columns:
      - name: product_id
        data_type: varchar
        description: Unique product identifier
        tests:
          - not_null
          - unique
      - name: product_name
        data_type: varchar
        description: Product name
        tests:
          - not_null
      - name: category
        data_type: varchar
        description: Product category
        tests:
          - not_null
      - name: price
        data_type: DECIMAL
        description: Product price
        tests:
          - not_null
      - name: stock_quantity
        data_type: INTEGER
        description: Stock quantity
        tests:
          - not_null
      - name: created_date
        data_type: date
        description: Creation date
        tests:
          - not_null

  - name: stg_payments
    description: Payments data cleaned and normalized
    config:
      contract:
        enforced: true
    columns:
      - name: payment_id
        data_type: varchar
        description: Unique payment identifier
        tests:
          - not_null
          - unique
      - name: order_id
        data_type: varchar
        description: Unique order identifier
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('stg_orders')
                field: order_id
      - name: payment_method
        data_type: varchar
        description: Payment method
        tests:
          - not_null
      - name: amount
        data_type: DECIMAL
        description: Payment amount
        tests:
          - not_null
      - name: payment_date
        data_type: DATE
        description: Payment date
        tests:
          - not_null
      - name: status
        data_type: varchar
        description: Payment status
        tests:
          - not_null
          - accepted_values:
              values: ['success', 'failed', 'refunded', 'pending', 'cancelled', 'returned']
